//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_401000(void);
int32_t function_401030(char * s);
int32_t function_401040(char * s);
int32_t function_401050(char * command);
int32_t function_401060(char * format, ...);
int64_t * function_401070(int64_t * s, int32_t c, int32_t n);
char * function_401080(char * s, int32_t n, struct _IO_FILE * stream);
int32_t function_401090(char * s1, char * s2);
int32_t function_4010a0(struct _IO_FILE * stream);
int32_t function_4010b0(char * s, char * format, ...);
char * function_4010c0(char * dest, char * src);
void function_4010d0(int32_t status);
int64_t function_401110(void);
int64_t function_401120(void);
int64_t function_401150(void);
int64_t function_401190(void);
int64_t function_4011c0(void);
int64_t function_4011c2(void);
int64_t function_4011f5(void);
int64_t function_40122c(void);
int64_t function_40142c(void);
int64_t function_4015f9(void);
int64_t function_4017c6(void);
int64_t function_401ce0(int64_t a1, int64_t a2, int64_t a3);
int64_t function_401d40(void);
int64_t function_401d44(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 0x4011c0; // 0x403e10
int64_t g2 = 0x401190; // 0x403e18
int64_t g3 = 0; // 0x403ff8
struct _IO_FILE * g4 = NULL; // 0x404160
struct _IO_FILE * g5 = NULL; // 0x404170
char g6 = 0; // 0x404178
char * g7; // 0x404180
int32_t g8;

// ------------------------ Functions -------------------------

// Address range: 0x401000 - 0x401017
int64_t function_401000(void) {
    int64_t result = 0; // 0x40100e
    if (g3 != 0) {
        // 0x401010
        __gmon_start__();
        result = &g8;
    }
    // 0x401012
    return result;
}

// Address range: 0x401030 - 0x401036
int32_t function_401030(char * s) {
    // 0x401030
    return puts(s);
}

// Address range: 0x401040 - 0x401046
int32_t function_401040(char * s) {
    // 0x401040
    return strlen(s);
}

// Address range: 0x401050 - 0x401056
int32_t function_401050(char * command) {
    // 0x401050
    return system(command);
}

// Address range: 0x401060 - 0x401066
int32_t function_401060(char * format, ...) {
    // 0x401060
    return printf(format);
}

// Address range: 0x401070 - 0x401076
int64_t * function_401070(int64_t * s, int32_t c, int32_t n) {
    // 0x401070
    return memset(s, c, n);
}

// Address range: 0x401080 - 0x401086
char * function_401080(char * s, int32_t n, struct _IO_FILE * stream) {
    // 0x401080
    return fgets(s, n, stream);
}

// Address range: 0x401090 - 0x401096
int32_t function_401090(char * s1, char * s2) {
    // 0x401090
    return strcmp(s1, s2);
}

// Address range: 0x4010a0 - 0x4010a6
int32_t function_4010a0(struct _IO_FILE * stream) {
    // 0x4010a0
    return fflush(stream);
}

// Address range: 0x4010b0 - 0x4010b6
int32_t function_4010b0(char * s, char * format, ...) {
    // 0x4010b0
    return sscanf(s, format);
}

// Address range: 0x4010c0 - 0x4010c6
char * function_4010c0(char * dest, char * src) {
    // 0x4010c0
    return strcat(dest, src);
}

// Address range: 0x4010d0 - 0x4010d6
void function_4010d0(int32_t status) {
    // 0x4010d0
    exit(status);
}

// Address range: 0x4010e0 - 0x40110b
int64_t entry_point(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x4010e0
    int64_t v1; // 0x4010e0
    __libc_start_main(0x4017c6, (int32_t)a4, (char **)&v1, (void (*)())0x401ce0, (void (*)())0x401d40, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x401110 - 0x401111
int64_t function_401110(void) {
    // 0x401110
    int64_t result; // 0x401110
    return result;
}

// Address range: 0x401120 - 0x401141
int64_t function_401120(void) {
    // 0x401120
    return (int64_t)&g4;
}

// Address range: 0x401150 - 0x401181
int64_t function_401150(void) {
    // 0x401150
    return 0;
}

// Address range: 0x401190 - 0x4011b1
int64_t function_401190(void) {
    // 0x401190
    if (g6 != 0) {
        // 0x4011b0
        int64_t result; // 0x401190
        return result;
    }
    int64_t result2 = function_401120(); // 0x40119d
    g6 = 1;
    return result2;
}

// Address range: 0x4011c0 - 0x4011c2
int64_t function_4011c0(void) {
    // 0x4011c0
    return function_401150();
}

// Address range: 0x4011c2 - 0x4011f5
int64_t function_4011c2(void) {
    // 0x4011c2
    printf("Welcome, Mr Shaibel...\n\n#");
    fflush(g4);
    return system("/bin/sh");
}

// Address range: 0x4011f5 - 0x40122c
int64_t function_4011f5(void) {
    // 0x4011f5
    puts("\n\n======== Chess Server Admin Area ========\n");
    printf("\nUnauthorized...");
    puts("\nThe Admin interface has been disabled in this version.");
    exit(0);
    // UNREACHABLE
}

// Address range: 0x40122c - 0x40142c
int64_t function_40122c(void) {
    // 0x40122c
    puts("\n\n============== Puzzle One =================\n");
    printf("  h    g    f    e    d    c    b    a  ");
    printf("\n ____ ____ ____ ____ ____ ____ ____ ____ \n");
    printf("|    | WK |    |    |    |    |    |    | 1");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("| WP |    |    |    |    |    |    | BR | 2");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("|    |    | BK |    |    |    |    |    | 3");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("|    |    |    |    |    |    |    |    | 4");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("|    | BP |    |    |    |    |    |    | 5");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("|    |    |    |    |    |    |    |    |");
    printf(" 6");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("|    |    |    |    |    |    |    |    |");
    printf(" 7");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("|    |    |    |    |    |    |    |    |");
    printf(" 8");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    puts("\nBlack to move. Choose and enter the best move :\n");
    printf("- Rh2\n- Ra1\n- h1\n\n>> ");
    fgets((char *)&g7, 128, g5);
    int64_t str; // bp-16, 0x40122c
    sscanf((char *)&g7, "%s", &str);
    if (strcmp((char *)&str, "Ra1") == 0) {
        // 0x401429
        return 0;
    }
    // 0x401413
    puts("\nIncorrect!!");
    exit(0);
    // UNREACHABLE
}

// Address range: 0x40142c - 0x4015f9
int64_t function_40142c(void) {
    // 0x40142c
    puts("\n\n============== Puzzle Two =================\n");
    printf("  a    b    c    d    e    f    g    h  ");
    printf("\n ____ ____ ____ ____ ____ ____ ____ ____ \n");
    printf("| BR |    |    |    |    | BR |    | BK | 8");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("| BP | BP |    |    |    |    |    |    | 7");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("|    |    | BP |    |    | BP |    | WP | 6");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("|    |    | WP |    | BP | BQ |    |    | 5");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("|    | WP |    | BP | WB |    |    |    | 4");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("|    |    |    |    |    |    | WQ |    | 3");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("| WP |    | WP |    |    |    | WP |    | 2");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("|    |    |    | WR |    |    | WK |    | 1");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    puts("\nWhite to move. Choose the best move :\n");
    printf("- Qg8\n- Bxf5\n- Qg7\n\n>> ");
    fgets((char *)&g7, 128, g5);
    int64_t str; // bp-16, 0x40142c
    sscanf((char *)&g7, "%s", &str);
    if (strcmp((char *)&str, "Qg7") == 0) {
        // 0x4015f6
        return 0;
    }
    // 0x4015e0
    puts("\nIncorrect!!");
    exit(0);
    // UNREACHABLE
}

// Address range: 0x4015f9 - 0x4017c6
int64_t function_4015f9(void) {
    // 0x4015f9
    puts("\n\n===== Puzzle Three : Beat Borgovotron =====\n");
    printf("  a    b    c    d    e    f    g    h  ");
    printf("\n ____ ____ ____ ____ ____ ____ ____ ____ \n");
    printf("|    |    |    |    | WQ |    |    |    | 8");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("|    |    |    |    |    |    | BK |    | 7");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("|    |    |    |    |    |    |    | BP | 6");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("|    | BP | WB | BP | BP |    |    |    | 5");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("|    | WP |    |    | BQ |    |    |    | 4");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("|    |    |    |    |    |    | WP |    | 3");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("|    |    |    |    | WK | WR |    |    | 2");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    printf("|    |    |    |    |    |    |    |    | 1");
    printf("\n|____|____|____|____|____|____|____|____|\n");
    puts("\nWhite to move. Choose the best move :\n");
    printf("- Kd2\n- Kf1\n- Kd1\n\n>> ");
    fgets((char *)&g7, 128, g5);
    int64_t str; // bp-16, 0x4015f9
    sscanf((char *)&g7, "%s", &str);
    if (strcmp((char *)&str, "Kd2") == 0) {
        // 0x4017c3
        return 0;
    }
    // 0x4017ad
    puts("\nIncorrect!!");
    exit(0);
    // UNREACHABLE
}

// Address range: 0x4017c6 - 0x401cd5
int64_t function_4017c6(void) {
    // 0x4017c6
    puts("\n================================================================");
    puts("                Q U E E N ' S    G A M B I T                    ");
    puts("================================================================\n");
    puts("                              ()    ");
    puts("                           .-:--:-. ");
    puts("                            \\____/  ");
    puts("                            {====}  ");
    puts("                             )__(   ");
    puts("                            /____\\  ");
    puts("                             |  |   ");
    puts("                            /____\\  ");
    puts("                           (======) ");
    puts("                           }======{ ");
    puts("                          (________)");
    puts("\n================================================================");
    puts("\nChess puzzles to train you brain.\nBecome a Grand Master.\n");
    puts("================================================================\n\n");
    puts("1) Play");
    puts("2) Chess Server Admin");
    puts("3) Quit");
    printf("\n>> ");
    int64_t str; // bp-176, 0x4017c6
    fgets((char *)&str, 8, g5);
    int64_t v1; // bp-204, 0x4017c6
    sscanf((char *)&str, "%d", &v1);
    int32_t v2 = v1; // 0x401917
    if (v2 != 1) {
        if (v2 != 2) {
            // 0x401cc4
            return puts("\nQuitting!");
        }
        // 0x401cab
        function_4011f5();
        // UNREACHABLE
    }
    // 0x401926
    printf("Enter your name:\n>> ");
    int64_t str2; // bp-200, 0x4017c6
    fgets((char *)&str2, 16, g5);
    int32_t len = strlen((char *)&str2); // 0x40195c
    int64_t v3; // bp-8, 0x4017c6
    *(char *)((int64_t)&v3 - 193 + (int64_t)len) = 0;
    int64_t str3; // bp-168, 0x4017c6
    int32_t len2 = strlen((char *)&str3); // 0x401981
    int64_t v4 = &str3; // 0x401989
    int64_t v5 = (int64_t)len2 + v4; // 0x401990
    *(int64_t *)v5 = 0x746172676e6f430a;
    *(int64_t *)(v5 + 8) = 0x736e6f6974616c75;
    *(int16_t *)(v5 + 16) = 32;
    strcat((char *)&str3, (char *)&str2);
    int64_t v6 = (int64_t)strlen((char *)&str3) + v4; // 0x4019e6
    *(int64_t *)v6 = 0x612072756f592021;
    *(int64_t *)(v6 + 8) = 0x617720726577736e;
    *(int64_t *)(v6 + 16) = 0x636572726f632073;
    *(int64_t *)(v6 + 24) = 0x72756f590a0a2174;
    *(int64_t *)(v6 + 32) = 0x676e696e6e697720;
    *(int64_t *)(v6 + 40) = 0x61772065766f6d20;
    *(int32_t *)(v6 + 48) = 0xa203a73;
    *(char *)(v6 + 52) = 0;
    strcat((char *)&str3, (char *)&g7);
    printf((char *)&str3);
    memset(&str3, 0, strlen((char *)&str3));
    function_40142c();
    int64_t v7 = (int64_t)strlen((char *)&str3) + v4; // 0x401aba
    *(int64_t *)v7 = 0x746172676e6f430a;
    *(int64_t *)(v7 + 8) = 0x736e6f6974616c75;
    *(int16_t *)(v7 + 16) = 32;
    strcat((char *)&str3, (char *)&str2);
    int64_t v8 = (int64_t)strlen((char *)&str3) + v4; // 0x401afc
    *(int64_t *)v8 = 0x612072756f592021;
    *(int64_t *)(v8 + 8) = 0x617720726577736e;
    *(int64_t *)(v8 + 16) = 0x636572726f632073;
    *(int64_t *)(v8 + 24) = 0x72756f590a0a2174;
    *(int64_t *)(v8 + 32) = 0x676e696e6e697720;
    *(int64_t *)(v8 + 40) = 0x61772065766f6d20;
    *(int32_t *)(v8 + 48) = 0xa203a73;
    *(char *)(v8 + 52) = 0;
    strcat((char *)&str3, (char *)&g7);
    printf((char *)&str3);
    memset(&str3, 0, strlen((char *)&str3));
    function_4015f9();
    int64_t v9 = (int64_t)strlen((char *)&str3) + v4; // 0x401bbc
    *(int64_t *)v9 = 0x746172676e6f430a;
    *(int64_t *)(v9 + 8) = 0x736e6f6974616c75;
    *(int16_t *)(v9 + 16) = 32;
    strcat((char *)&str3, (char *)&str2);
    int64_t v10 = (int64_t)strlen((char *)&str3) + v4; // 0x401bfe
    *(int64_t *)v10 = 0x7720746168540a21;
    *(int64_t *)(v10 + 8) = 0x6620656874207361;
    *(int64_t *)(v10 + 16) = 0x7a7570206c616e69;
    *(int64_t *)(v10 + 24) = 0xa0a212121656c7a;
    *(int64_t *)(v10 + 32) = 0x6e69572072756f59;
    *(int64_t *)(v10 + 40) = 0x766f6d20676e696e;
    *(int64_t *)(v10 + 48) = 0x203a736177207365;
    *(int16_t *)(v10 + 56) = 10;
    strcat((char *)&str3, (char *)&g7);
    printf((char *)&str3);
    // 0x401cc4
    return puts("\n\nYou defeated the Borgovotron!\nKeep training and you'll be a Grand Master in no time!!!\n");
}

// Address range: 0x401ce0 - 0x401d3d
int64_t function_401ce0(int64_t a1, int64_t a2, int64_t a3) {
    int64_t result = function_401000(); // 0x401d08
    if ((int64_t)&g2 - (int64_t)&g1 >> 3 == 0) {
        // 0x401d2e
        return result;
    }
    int64_t v1 = 0; // 0x401d11
    while (v1 + 1 != (int64_t)&g2 - (int64_t)&g1 >> 3) {
        // 0x401d18
        v1++;
    }
    // 0x401d2e
    return result;
}

// Address range: 0x401d40 - 0x401d41
int64_t function_401d40(void) {
    // 0x401d40
    int64_t result; // 0x401d40
    return result;
}

// Address range: 0x401d44 - 0x401d4d
int64_t function_401d44(void) {
    // 0x401d44
    int64_t result; // 0x401d44
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// void __gmon_start__(void);
// int __libc_start_main(int *(main)(int, char **, char **), int argc, char ** ubp_av, void(* init)(void), void(* fini)(void), void(* rtld_fini)(void), void(* stack_end));
// void exit(int status);
// int fflush(FILE * stream);
// char * fgets(char * restrict s, int n, FILE * restrict stream);
// void * memset(void * s, int c, size_t n);
// int printf(const char * restrict format, ...);
// int puts(const char * s);
// int sscanf(const char * restrict s, const char * restrict format, ...);
// char * strcat(char * restrict dest, const char * restrict src);
// int strcmp(const char * s1, const char * s2);
// size_t strlen(const char * s);
// int system(const char * command);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (10.2.0)
// Detected functions: 27
